apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: nmost
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  jwtRules:
    - issuer: "auth-service"
      jwksUri: "http://auth-service.nmost.svc.cluster.local:8080/jwts"
      forwardOriginalToken: true

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: nmost
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  action: DENY
  rules:
    - {}  
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: grpc-auth-policy
  namespace: nmost
spec:
  selector:
    matchLabels:
      app: grpc-gateway
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            methods: ["POST"]
            paths: ["/api/v1/news"]
      when:
        - key: request.auth.claims[roles]
          values: ["admin"]
    - to:
        - operation:
            methods: ["GET"]
            paths: [
              "/api/v1/news",
              "/api/v1/news/*",
              "/api/v1/media/*",
              "/api/v1/ai/*",
              "/api/v1/tags/*",
              "/api/v1/category/*"
            ]
    - to:
        - operation:
            methods: ["OPTIONS"]
