apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-gateway
  template:
    metadata:
      labels:
        app: grpc-gateway
      annotations:
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/includeInboundPorts: "8080"  # Только входящий трафик на порт 8080
        traffic.sidecar.istio.io/excludeOutboundPorts: "3001"  # Исключаем исходящий трафик к микросервисам
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_HTTP_PROTOCOL: "http"
    spec:
      containers:
      - name: grpc-gateway
        image: ghcr.io/impit-mpit/api-gateway-master:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NEWS_SERVICE
          value: "news-service:3001"
        - name: MEDIA_SERVICE
          value: "media-service:3001"
        - name: AI_SERVICE
          value: "ai-service:3001"
        - name: TAGS_SERVICE
          value: "tags-service:3001"
        - name: CATEGORY_SERVICE
          value: "category-service:3001"
        - name: AUTH_SERVICE
          value: "auth-service-grpc:3001"
        - name: SPECIALIST_SERVICE
          value: "specialist-service:3001"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-gateway
spec:
  selector:
    app: grpc-gateway
  ports:
  - port: 80
    targetPort: 8080
    name: http